### ISSUE TITLE
NO DETECTED DEVICE IN ADB

### ISSUE THREAD

**Issue by cint1993** [iamromulan/quectel-rgmii-configuration-notes#4]
Thank you for this guide.  This is a great help for us and the 5g community. 

I'm having a problem Sir, I have enabled ADB on my Waveshare 5g to Eth [https://www.waveshare.com/5g-m.2-to-gigabit-eth.html]  , followed the guide 100% yet this won't be detected  when I type adb devices on adb and fastboot++ command prompt. I know this is odd, is there a work around when trying to access ADB of RM520n? Do I need to downgrade my module firmware? btw I am using the latest firmware and installed the all required driver  for windows. 

Here is the screenshot when trying to access ADB 

![received_393387810166097](https://github.com/iamromulan/quectel-rgmii-configuration-notes/assets/64637972/07718266-5355-4d07-92a4-0471609e43e3)

Enabled ADB: 

![received_777143304391061](https://github.com/iamromulan/quectel-rgmii-configuration-notes/assets/64637972/f6721189-86a3-4521-9cee-d6e187036aa0)

**Comment by dr-dolomite** [comment]
You also messaged me directly through messenger and I believe that this is not an issue with Simpleadmin or other services that our repo offers. Kindly recheck if you did enabled the ADB on your module by providing it's unique code and also sending the enabling command. Also, it is also possible that the issue might be caused by your M.2 to ETH board since we haven't tried testing that. - Rus

**Comment by iamromulan** [comment]
@cint1993 What's that emulator device? 
Also, check in device manager toward the bottom in your USB devices. Should see something called Adb Interface. If it mentions Q something or Quectel that's the wrong driver.

**Comment by cint1993** [comment]
I just found out a solution sir. The issue is my operating system permission settings. I used linux and it solved the issue. Cheers to more development with RGMII. Hoping for more updates 🎉
